### PR TITLE
Improve compatibility in complex cross-targeting scenarios.

### PR DESCRIPTION
**Pull request by Chryssie**
This allows for a dll compiled against netstandard2.0 with this as a depedency to be consumed from another dll compiled against net6.0 (or greater) without requiring the netstandard2.0 dll to multitarget netstandard2.0 and net6.0.

This is achieved by the removal of the conditional remove of the output dlls in the package, instead opting for conditional exclusion of most of the codebase except for three `[assembly: TypeForwardedTo()]` declarations which allow the compiler and runtimes to swap out the type decalrations here for the real ones in net6.0.

### CODE REVIEW

**Comment by OlegRa** [comment]
@Chryssie thanks a lot for this PR and your help. I've spent some time trying to understand/reproduce the original problem with transitive dependency and now I know the root cause better. Proposed changes solve this problem, but I have some ideas to improve it. We have two options:

1. I can merge your PR as-is and apply my changes in a separate commit. This way is simple and straightforward but I want to try another approach.
2. You will enable the [Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) option for this PR and I'll add my changes to the existing PR. it will make Git history clearer.

Please, tell me which option works better for you and I'll process with the next step.

**Comment by Chryssie** [comment]
@OlegRa I've enabled edits by maintainers so you should be able to make your changes now.

**Comment by OlegRa** [comment]
@all-contributors bot!

**Comment by OlegRa** [comment]
@all-contributors please add @Chryssie  for code.

**Pull request merged**
